#!/usr/bin/env php
<?php

/**
 * Bioteaweb API
 *
 * A rest API frontend and indexer for the Biotea RDF project
 *
 * @link    http://biotea.idiginfo.org/api
 * @author  Casey McLaughlin <caseyamcl@gmail.com>
 * @license Copyright (c) Florida State University - All Rights Reserved
 */

// ------------------------------------------------------------------

/**
 * @file Console File
 */

// ------------------------------------------------------------------

/*
 * Uses
 */
use FOS\Rest\Util\FormatNegotiator;
use Symfony\Component\Console\Application;

// ------------------------------------------------------------------

/*
 * Bootstrap
 */
require(__DIR__ . '/../src/bootstrap.php');

// ------------------------------------------------------------------

/*
 * CLI Specific Libraries
 */

//Libraries
$app['consoleapp'] = new Application('Biotea API Console Utilities');

//Commands
$app['consoleapp']->add(new Bioteawebapi\Commands\SchemaBuild($app));
$app['consoleapp']->add(new Bioteawebapi\Commands\DocsBuildZips($app));
$app['consoleapp']->add(new Bioteawebapi\Commands\DocsDump($app));
$app['consoleapp']->add(new Bioteawebapi\Commands\DocsIndex($app));
$app['consoleapp']->add(new Bioteawebapi\Commands\DocsClear($app));
$app['consoleapp']->add(new Bioteawebapi\Commands\DocsStats($app));
$app['consoleapp']->add(new Bioteawebapi\Commands\Sandbox($app));
$app['consoleapp']->add(new Bioteawebapi\Commands\MaterialsMethods($app));


// ------------------------------------------------------------------

/*
 * Run
 */
$app['consoleapp']->run();

/* EOF: run.php */