#!/usr/bin/env php
<?php

/**
 * Bioteaweb API
 *
 * A rest API frontend and indexer for the Biotea RDF project
 *
 * @link    http://biotea.idiginfo.org/api
 * @author  Casey McLaughlin <caseyamcl@gmail.com>
 * @license Copyright (c) Florida State University - All Rights Reserved
 */

// ------------------------------------------------------------------

/**
 * @file Console File
 */

// ------------------------------------------------------------------

/*
 * Uses
 */
use FOS\Rest\Util\FormatNegotiator;
use Symfony\Component\Console\Application;

// ------------------------------------------------------------------

/*
 * Bootstrap
 */
require(__DIR__ . '/../src/bootstrap.php');

// ------------------------------------------------------------------

/*
 * CLI Specific Libraries
 */

//Libraries
$app['consoleapp'] = new Application();

//Commands
$app['consoleapp']->add(new Bioteawebapi\Commands\Dummy($app));
$app['consoleapp']->add(new Bioteawebapi\Commands\BuildSchema($app));
$app['consoleapp']->add(new Bioteawebapi\Commands\DumpDocSets($app));
$app['consoleapp']->add(new Bioteawebapi\Commands\Index($app));

// ------------------------------------------------------------------

/*
 * Run
 */
$app['consoleapp']->run();

/* EOF: run.php */