
Biojs.Graph=Biojs.extend({constructor:function(options){this._container=jQuery('#'+this.opt.target);this._container.addClass('Graph');this._init();},_init:function(){this._jsPlumb=jsPlumb.getInstance();this._nodeIdCounter=0;var d=this._jsPlumb.Defaults;d.Anchor=this.opt.anchor;d.PaintStyle=this.opt.paintStyle;d.Endpoint=this.opt.endPoint;d.EndpointStyle=this.opt.endPointStyle;d.Scope=this._container.attr('id');d.Connector=this.opt.connector;if(this.opt.viewport==undefined){this.opt.viewport={xMin:this._container.offset().left,xMax:this._container.offset().left+(this._container.width()>0?this._container.width():jQuery(window).width()),yMin:this._container.offset().top,yMax:this._container.offset().top+(this._container.height()>0?this._container.height():jQuery(window).height())};}
this.opt.attractionConstant=this.opt.influenceConstant/(this.opt.normalDistance*this.opt.normalDistance*this.opt.normalDistance);},opt:{target:"YourOwnDivId",anchor:"Continuous",paintStyle:{lineWidth:2,strokeStyle:"#456"},endPoint:"Dot",endPointStyle:{fillStyle:"myEndpoint",radius:2},connector:["Bezier",{curviness:50}],normalDistance:100,influenceConstant:7,damping:0.96,stoppingVelocity:0.1,minimumStartingVelocity:1,maximumStartingVelocity:5,attractionConstant:7/(100*100*100),repellingFactor:70,fps:100,animate:true,viewport:undefined},eventTypes:["onClick"],addLink:function(source,target,label,id){var idSource=source;var idTarget=target;var link;var settings;var self=this;if("string"!=typeof source){idSource=jQuery(source).attr('id');}
if("string"!=typeof target){idTarget=jQuery(target).attr('id');}
settings={source:idSource,target:idTarget,overlays:[["Label",{cssClass:"label",label:label,id:"label",events:{"click":function(label,evt){alert("clicked on label for connection "+label.component.id);}}}]]};if(id!=undefined){settings.id=id;}
try{link=this._jsPlumb.connect(settings);var overlay=link.getOverlay("label").hide();link.bind("mouseenter",function(conn){var overlay=conn.getOverlay("label");overlay.show();}).bind("mouseexit",function(conn){var overlay=conn.getOverlay("label");overlay.hide();});}catch(e){Biojs.console.log(e);}
var nodeSource=this._nodes[idSource];var nodeTarget=this._nodes[idTarget];nodeSource.links[idTarget]=nodeTarget;nodeTarget.links[idSource]=nodeSource;nodeSource.linksLength++;nodeTarget.linksLength++;nodeSource.moving=true;nodeTarget.moving=true;this.start();return link;},removeLink:function(link){var cnn=link;if("string"==typeof link){var i;var conns=this._jsPlumb.getConnections();for(var i=0;i<conns.length&&(link!=conns[i].getId());i++){;}
cnn=(i<conns.length)?conns[i]:{};}
if(cnn.hasOwnProperty("removeOverlays")){delete this._nodes[cnn.sourceId].links[cnn.targetId];delete this._nodes[cnn.targetId].links[cnn.sourceId];cnn.removeOverlays();for(var e in cnn.endpoints){this._jsPlumb.deleteEndpoint(cnn.endpoints[e]);}
this.start();return true;}
return false;},removeLinksFromNode:function(node){var id=("string"==typeof node)?node:node.id;var conns=(this._jsPlumb.getConnections({source:id})).concat(this._jsPlumb.getConnections({target:id}));for(var c in conns){this.removeLink(conns[c]);}
this._jsPlumb.removeAllEndpoints(node);},addNode:function(data){var node=jQuery('<div></div>');var self=this;if("string"==typeof data){if(data.match(/<\/?.*(?=>|\s.*>)\/?.*?>/g)){node=jQuery(data);}else{node.attr('id',(!Biojs.Utils.isEmpty(data))?data:"node"+this._nodeIdCounter++);}}else{node=jQuery(data);}
node.id=node.attr('id');if(Biojs.Utils.isEmpty(node.id)){node.id="node"+this._nodeIdCounter++;node.attr('id',node.id);}
node.x=this.opt.viewport.xMin+Math.floor(Math.random()*this.opt.viewport.xMax/3);node.y=this.opt.viewport.yMin+Math.floor(Math.random()*this.opt.viewport.yMax/3);node.velocity={x:0,y:0};node.mass=1;node.fixed=false;node.moving=true;node.links={};node.linksLength=0;this._nodes[node.id]=node;node.css({position:"absolute",top:node.x,left:node.y}).addClass('node').appendTo(this._container);this._jsPlumb.draggable(node.id);var closeButton=jQuery('<span class="close-btn-18" title="Close">Close</span>').click(function(){self.removeNode(node);}).hide().prependTo(node);node.mousedown(function(){jQuery(window).mousemove(function(){node.x=node.offset().left;node.y=node.offset().top;self._setPivotNode(node);for(var i in node.links){node.links[i].moving=true;}
self.start();});}).mouseup(function(){jQuery(window).unbind("mousemove");self._releasePivotNode(node);}).mouseover(function(){closeButton.show();}).mouseout(function(){closeButton.hide();});this.start();return node;},getNode:function(id){return("string"==typeof id)?this._nodes[id]:{};},getAllNodes:function(){return this._nodes;},removeNode:function(node){var nodeObj=("string"==typeof node)?this._nodes[node]:node;for(var i in nodeObj.links){nodeObj.links[i].moving=true;}
this.removeLinksFromNode(nodeObj);delete this._nodes[nodeObj.id];nodeObj.remove();this.start();},removeAllNodes:function(){for(var i in this._nodes){this.removeNode(this._nodes[i]);}},start:function(){var self=this;if(!this._running&&this.opt.animate){this._running=true;this._drawId=setInterval(function(){self._forceBasedAlgorithm(self.opt);},1000/this.opt.fps);}},stop:function(){if(this._running){clearInterval(this._drawId);this._running=false;}},animate:function(value){this.stop();this.opt.animate=value;this.start();},setDistance:function(distance){this.stop();this.opt.normalDistance=distance;this.opt.attractionConstant=this.opt.influenceConstant/(distance*distance*distance);this._moveEveryThing();},setDamping:function(value){this.opt.damping=(100-value)/100;this._moveEveryThing();},setRepellingFactor:function(factor){this.opt.repellingFactor=factor;this._moveEveryThing();},setVelocity:function(fps){this.stop();this.opt.fps=fps;this._moveEveryThing();},setAttractionConstant:function(value){this.opt.attractionConstant=value;this._moveEveryThing();},setViewPort:function(window){if(window!=undefined){this.opt.viewport.xMin=window.xMin?window.xMin:this.opt.viewport.xMin;this.opt.viewport.xMax=window.xMax?window.xMax:this.opt.viewport.xMax;this.opt.viewport.yMin=window.yMin?window.yMin:this.opt.viewport.yMin;this.opt.viewport.yMax=window.yMax?window.yMax:this.opt.viewport.yMax;}},_nodes:[],_pivotNode:undefined,_equilibrium:false,running:false,_moveEveryThing:function(){this.stop();for(var j in this._nodes){this._nodes[j].moving=true;}
this.start();},_setPivotNode:function(node){if(this._pivotNode==undefined){this._pivotNode=node;}else if(node!=this._pivotNode){this._releasePivotNode(this._pivotNode,0);this._pivotNode=node;}else{this._cancelPivotTimer(node);}
node.fixed=true;},_releasePivotNode:function(node,time){var ms=(time!=undefined)?time:1000;if(ms>0){this._setPivotTimer(node,ms);}else{this._cancelPivotTimer(node);}},_setPivotTimer:function(node,ms){var self=this;this._cancelPivotTimer(node);node.fixed=true;node.waitingReleaseId=setInterval(function(){if(self._equilibrium){self._cancelPivotTimer(node);}},ms);},_cancelPivotTimer:function(node){node.fixed=false;if(node.waitingReleaseId>0){clearInterval(node.waitingReleaseId);node.waitingReleaseId=0;}},_forceBasedAlgorithm:function(o){this._equilibrium=true;var repellingForce,attractingForce,node,otherNode,square,direction;var numberOfNodes=this._nodes.length;var numberOfStoppedNodes=0;var startingVelocityDelta=o.maximumStartingVelocity-o.minimumStartingVelocity;for(var i in this._nodes){node=this._nodes[i];square=this._createSquare(node,o.influenceConstant*o.normalDistance);for(var j in this._nodes){otherNode=this._nodes[j];if(i!=j){if(this._withinSquare(otherNode,square)){repellingForce=this._repelling(node,otherNode);node.velocity.x+=repellingForce.x;node.velocity.y+=repellingForce.y;}}
if(j==0&&(!otherNode.moving||otherNode.fixed)){numberOfStoppedNodes++;}}
for(var k in node.links){attractingForce=this._attracting(node,node.links[k]);node.velocity.x+=attractingForce.x/node.linksLength;node.velocity.y+=attractingForce.y/node.linksLength;}
node.velocity.x*=o.damping;node.velocity.y*=o.damping;node.velocityLength=this._absolute(node.velocity.x)+this._absolute(node.velocity.y);if(node.velocityLength<=o.stoppingVelocity){node.moving=false;}
if(node.velocityLength>=o.minimumStartingVelocity+startingVelocityDelta*numberOfStoppedNodes/numberOfNodes){node.moving=true;}
this._setNodeDirection(node,this.opt.viewport);if(node.moving&&!node.fixed){this._equilibrium=false;node.x+=node.velocity.x;node.y+=node.velocity.y;}
node.offset({left:node.x,top:node.y});this._jsPlumb.repaint(node.id);}
if(this._equilibrium){this.stop();}
return this._equilibrium;},_createSquare:function(node,offset){return{xMin:node.x-offset,xMax:node.x+offset+node.width(),yMin:node.y-offset,yMax:node.y+offset+node.height()};},_withinSquare:function(otherNode,square){return otherNode.x>=square.xMin&&otherNode.x<=square.xMax&&otherNode.y>=square.yMin&&otherNode.y<=square.yMax;},_setNodeDirection:function(node,square){if(((node.x<=square.xMin)&&(node.velocity.x<0))||(((node.x+node.width())>=square.xMax)&&(node.velocity.x>0))){node.velocity.x*=-1;}
if(((node.y<=square.yMin)&&(node.velocity.y<0))||(((node.y+node.height())>=square.yMax)&&(node.velocity.y>0))){node.velocity.y*=-1;}},_absolute:function(value){return value<0?-value:value;},_square:function(value){return value*value;},_manhattanDistance:function(node,otherNode){var d=this._absolute(otherNode.x-node.x)+this._absolute(otherNode.y-node.y);if(d>0)return d;node.x+=1;return 1;},_repelling:function(node,otherNode){var repelling=this.opt.repellingFactor/this._square(this._manhattanDistance(node,otherNode));return{x:repelling*(node.x-otherNode.x),y:repelling*(node.y-otherNode.y)};},_attracting:function(node,otherNode){var attraction=this.opt.attractionConstant*this._manhattanDistance(node,otherNode);return{x:(otherNode.x-node.x)*attraction,y:(otherNode.y-node.y)*attraction};}});